[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1_000_000
via_ir = true
verbosity = 2
fuzz = { runs = 256 }
gas_reports = ["AttestationRegistry", "FederationAggregator"]
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "solady/=lib/solady/src/",
  "forge-std/=lib/forge-std/src/",
]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
